<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Evergine.Common" Version="2026.5.21.1068-nightly" />
    <PackageReference Include="Evergine.Components" Version="2026.5.21.1068-nightly" />
    <PackageReference Include="Evergine.Framework" Version="2026.5.21.1068-nightly" />
    <PackageReference Include="Evergine.Editor.Extension" Version="2026.5.21.1068-nightly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EverSneaks\EverSneaks.csproj" />
  </ItemGroup>
</Project>